In [3]:
import numpy as np

In [6]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [19]:
a = np.array([1 ,2 ,3.1 ,4 ])
a

array([1. , 2. , 3.1, 4. ])

In [20]:
a.dtype

dtype('float64')

In [21]:
b = np.array([5,3,7,5,6,3,56,3,6,4])
b

array([ 5,  3,  7,  5,  6,  3, 56,  3,  6,  4])

In [22]:
b.dtype

dtype('int32')

In [23]:
b.size

10

In [27]:
#  [2021, 2023, 2025, 2025.6]
p = np.array([2021,2023,2025,2025.6])
print("DataType:", p.dtype)
print("Size:", p.size)

DataType: float64
Size: 4


In [28]:
p

array([2021. , 2023. , 2025. , 2025.6])

In [29]:
p.ndim

1

In [30]:
ar2 = np.array( [ [1,2], [2,3]  ] )

In [31]:
ar2

array([[1, 2],
       [2, 3]])

In [32]:
ar2.ndim

2

In [35]:
# h=np.array( [ [ [1,2,3],[5,7]]])

In [36]:
ar3 = np.array([ [ [ 1, 2, 3 ] ] ])
ar3

array([[[1, 2, 3]]])

In [37]:
ar3.ndim

3

In [38]:
ar3 = np.array(  [ [1,2], [1,2] ] )
ar3.ndim

2

In [40]:
ar2 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
ar2.ndim

3

In [43]:
ar3 = np.array([ [ [2,3,4], [1,4,3]], [[4,5,4], [4,8,3]] ])
ar3

array([[[2, 3, 4],
        [1, 4, 3]],

       [[4, 5, 4],
        [4, 8, 3]]])

In [42]:
ar3.shape

(2, 2, 2)

In [46]:
ar4 = np.array([ [ 1,2,3,4,5 ] ])
ar4.shape

(1, 5)

In [48]:
ar4 = np.array([ [1,2,4], [1,3,9] ])
ar4.shape

(2, 3)

In [49]:
ar5 = np.array([ [ [1,2,4], [4,3,1]], [[1,5,3], [5,3,5]] ])
ar5

array([[[1, 2, 4],
        [4, 3, 1]],

       [[1, 5, 3],
        [5, 3, 5]]])

In [50]:
ar5.shape

(2, 2, 3)

In [ ]:
ar6 = np.array([[1,2,3,4], [4,5,6,7]])
# dim
# data type
# shape
# size

In [65]:
import numpy as np
ar1=np.array([[1,2,3,4],[4,5,6,7]])
print(ar1.ndim)
print(ar1.shape)
print(ar1.dtype)
print(ar1.size)


2
(2, 4)
int32
8


In [74]:
ar2=np.array([[1,2,3,4,5],[4,5,6,7]])
ar2

array([list([1, 2, 3, 4, 5]), list([4, 5, 6, 7])], dtype=object)

In [75]:
ar2=np.array([[1,2,3,4],[4,5,6,7]])
ar2

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

# Numpy Arange

In [66]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [67]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [69]:
np.arange(10000000)

array([      0,       1,       2, ..., 9999997, 9999998, 9999999])

# Reshape

In [71]:
a = np.arange(100).reshape(10,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [72]:
a.shape

(10, 10)

In [73]:
b = np.arange(10).reshape(2,5)
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [76]:
b = np.arange(10).reshape(3,4)
# reshape 10  1,10 - 2,5 - 5,2 - 10,1

ValueError: cannot reshape array of size 10 into shape (3,4)

In [80]:
b = np.arange(10).reshape(1,1,1,1,1,1,10)
b

array([[[[[[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]]]]]])

In [84]:
b = np.arange(12).reshape(2,2,3)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [86]:
b.shape

(2, 2, 3)

In [89]:
a = np.arange(12).reshape(2,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [90]:
a.shape

(2, 6)

In [92]:
a.size

12

# Zeros

In [94]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [96]:
# create an array in shape of 4,5 containing all zeroes
a = np.zeros(20).reshape(4,5)
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Random

In [116]:
np.random.rand()

0.8660209121268913

In [123]:
np.random.randint(1000)

622

In [124]:
np.random.randint(0, 1000, 100)

array([597, 380, 644, 455, 181, 121, 297, 450, 450, 903,  16, 729, 476,
       475, 601, 847,  61, 594, 208, 115, 165, 976, 244, 501, 843, 246,
       819, 982, 916, 193, 324, 379, 914, 869, 452, 183, 199, 965, 546,
       516, 744, 694, 413, 251, 672, 585, 709, 327, 171, 399, 159, 496,
       879, 500,  63, 990, 874, 438, 484, 316, 488, 499, 714, 390, 132,
       252, 886, 491, 194, 331, 558, 113, 453,  47, 694,  41, 364, 807,
       162,  52, 455, 857,  50, 937, 915, 943, 525, 722, 457, 514, 122,
       580, 522, 981, 363, 810,  88, 380, 911, 121])

In [125]:
# create an array with 200 random int shaped into 20,10
np.random.randint(0,2000,200).reshape(20,10)

array([[1519, 1641, 1896, 1448,  496,  243, 1822,  667, 1532, 1314],
       [1993,  768,  588,  736,  963, 1109, 1151, 1620,  845,  676],
       [1282, 1325,  214,  268, 1111, 1419,  786, 1605, 1320,  480],
       [ 143, 1940, 1330,  243, 1205,  613,  422,  653, 1898,  815],
       [  25, 1099,   56,  501,  207,  258,  975, 1734, 1822, 1279],
       [1090, 1218,  101, 1269, 1949, 1658,  532, 1204, 1528,  505],
       [ 498, 1710, 1901, 1819,   26,  415,  792, 1810, 1878, 1488],
       [ 889,   62, 1545, 1523,  452, 1469,  700, 1684, 1969, 1073],
       [ 366,  710, 1747,  457, 1572, 1454, 1150, 1168, 1575, 1749],
       [1113,  180, 1984,  170,  372,  314,  328, 1729,  536, 1782],
       [1773,  987,  509, 1307, 1130,  913, 1848,  765,  635,  134],
       [ 711, 1000,  343,  250,  334,  696, 1808, 1678,  593,  416],
       [1726, 1549,  576, 1505,  484,  526, 1306, 1738, 1636,  354],
       [1429,  145, 1119,  610,  340, 1290, 1140,  421,  597, 1237],
       [ 222, 1087, 1887, 1555, 19

# Ravel

In [141]:
ar2 = np.array([[1,2,3,4,5],[4,5,6,7,8]])
ar2.shape

(2, 5)

In [142]:
ar2.ravel()

array([1, 2, 3, 4, 5, 4, 5, 6, 7, 8])

# Floor and Ceil

In [149]:
arr1 = np.array([10.5, 5.12, 9.16, 6.95])
arr1

array([10.5 ,  5.12,  9.16,  6.95])

In [150]:
np.floor(arr1)

array([10.,  5.,  9.,  6.])

In [151]:
np.ceil(arr1)

array([11.,  6., 10.,  7.])

# Stacking

In [153]:
arr1 = np.arange(10).reshape(2,5)
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [154]:
arr2 = np.arange(20).reshape(4,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [156]:
np.vstack((arr1, arr2))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [157]:
np.hstack((arr1, arr2))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 4

In [158]:
arr1 = np.arange(20).reshape(4,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [159]:
arr2 = np.arange(40).reshape(4,10)
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [161]:
np.hstack((arr1, arr2))

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [15, 16, 17, 18, 19, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

# Split

In [162]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [163]:
arr2.shape

(4, 10)

In [166]:
np.hsplit(arr2, 5)

[array([[ 0,  1],
        [10, 11],
        [20, 21],
        [30, 31]]),
 array([[ 2,  3],
        [12, 13],
        [22, 23],
        [32, 33]]),
 array([[ 4,  5],
        [14, 15],
        [24, 25],
        [34, 35]]),
 array([[ 6,  7],
        [16, 17],
        [26, 27],
        [36, 37]]),
 array([[ 8,  9],
        [18, 19],
        [28, 29],
        [38, 39]])]

In [167]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [168]:
np.vsplit(arr2, 2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])]

In [172]:
np.hsplit(arr1,5)

[array([[ 0],
        [ 5],
        [10],
        [15]]),
 array([[ 1],
        [ 6],
        [11],
        [16]]),
 array([[ 2],
        [ 7],
        [12],
        [17]]),
 array([[ 3],
        [ 8],
        [13],
        [18]]),
 array([[ 4],
        [ 9],
        [14],
        [19]])]

In [171]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [179]:
np.arange(10).reshape(2,5) * 5

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45]])